app/urls.py
from django.urls import path
from . import views as v

app_name='app'
urlpatterns = [
    path('',v.index,name='index'),
    path('<int:id>/edite', v.edite, name='edite'),
    path('<int:id>/delete', v.delete, name='delete'),

]

project/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app.urls',namespace='app'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app/models.py
from django.db import models

# Create your models here.


class Task(models.Model):
    title=models.CharField(max_length=200)
    completed=models.BooleanField(default=False)
    created=models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return self.title

app/forms.py
from django import forms
from .models import Task

class TaskForm(forms.ModelForm):
    class Meta:
        model=Task
        fields='__all__'

app/views.py
from django.shortcuts import get_object_or_404, render, redirect
from .models import Task
from .forms import TaskForm
# Create your views here.


def index(request):
    tasks = Task.objects.all()
    form = TaskForm()
    if request.method == 'POST':
        form = TaskForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/')

    context = {
        'tasks': tasks,
        'form': form,
    }
    return render(request, 'index.html', context)


def edite(request,id):
    task=get_object_or_404(Task,id=id)
    form = TaskForm(instance=task)
    if request.method =='POST':
        form = TaskForm(request.POST,instance=task)
        if form.is_valid():
            form.save()
            return redirect('/')

    context={
        'form':form,
    }
    return render(request, 'edite.html', context)


def delete(request,id):
    task=get_object_or_404(Task,id=id)
    if request.method=='POST':
        task.delete()
        return redirect('/')
    
    context={
        'task':task,
    }
    return render(request, 'delete.html', context)

app/templates/delete.html
{% extends 'base.html' %}
{% load bootstrap %}
{% block content %}
    <div class="container mx-auto">
        <span class="d-block p-2 bg-light text-black">
            <div class="row mx-auto col-xs-1"  align="center">
                <h3>are you sure you want delete "{{task}} " ?</h3>
                <br>
            </div>
        </span>
        <form method='POST' action='' class="form-inline my-2 my-lg-0container mx-auto col-xs-1">
            <div class="row">
                    {% csrf_token %}
                    
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">delete</button>
        </div>
        </form>




    </div>

{% endblock content %}

app/templates/edite.html
{% extends 'base.html' %}
{% load bootstrap %}
{% block content %}

    <div class="container mx-auto">
        <form method='POST' action='' class="form-inline my-2 my-lg-0">
            {% csrf_token %}
            {{ form|bootstrap }}
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Edite</button>

        </form>
       



    </div>


{% endblock content %}

app/templates/index.html
{% extends 'base.html' %}
{% load bootstrap %}
{% block content %}
  
    <div class="container mx-auto">
        <h1>Incomplete Tasks</h1>
    
        
        <form method='POST' action='/' class="form-inline my-2 my-lg-0container mx-auto col-xs-1" >
            <div class="row">
                
                {% csrf_token %}
                <div class="col">
                {{ form.title|bootstrap }}
                </div>
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Add</button>
            </div>
        </form>
        <br>
        {% for task in tasks %}
        <div class="container mx-auto col-xs-1" >
            <span class="d-block p-2 bg-light text-black">
                <div class="row">
                    <div class="col-lg-7">
                        
                        {% if task.completed == 'True'  %}
                            <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>>{{task}}</strike>
                        
                        {% else %}
                             <strong>{{task}}</strong>
                        {% endif %}
                    </div>
                    <div class="col-lg-3">
                         <a href="{% url 'app:edite' task.id %}" class="badge badge-success">edite task</a>
                        <a href="{% url 'app:delete' task.id %}" class="badge badge-danger">delete task</a>
                    </div>
                <br><br>
                </div>
            </span>
        </div>
        {% endfor %}


    </div>

{% endblock content %}

templates/base.html
{% load bootstrap %}
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
        integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <title>To Do App</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto|Varela+Round|Raleway">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
    <style>
         body {
            background: #eeeeee;
            font-family: 'Varela Round', sans-serif;
        }
    
        .form-inline {
            display: inline-block;
        }
    
        .navbar-header.col {
            padding: 0 !important;
        }
    
        .navbar {
            background: #fff;
            padding-left: 16px;
            padding-right: 16px;
            border-bottom: 1px solid #d6d6d6;
            box-shadow: 0 0 4px rgba(0, 0, 0, .1);
        }
    
        .nav-link {
            margin: 0 5px;
        }
    
        .nav-link img {
            border-radius: 50%;
            width: 36px;
            height: 36px;
            margin: -8px 0;
            float: left;
            margin-right: 10px;
        }
    
        .navbar .navbar-brand {
            color: #555;
            padding-left: 0;
            font-size: 20px;
            padding-right: 50px;
            font-family: 'Raleway', sans-serif;
        }
    
        .navbar .navbar-brand b {
            font-weight: bold;
            color: #eb5844;
        }
    
        .navbar .navbar-nav a:hover,
        .navbar .navbar-nav a:focus {
            color: #f08373 !important;
        }
    
        .navbar .navbar-nav a.active,
        .navbar .navbar-nav a.active:hover {
            color: #eb5844 !important;
            background: transparent !important;
        }
    
        .search-box {
            position: relative;
        }
    
        .search-box input.form-control {
            padding-right: 35px;
            border-radius: 0;
            padding-left: 0;
            border-width: 0 0 1px 0;
            box-shadow: none;
        }
    
        .search-box input.form-control:focus {
            border-color: #f08373;
        }
    
        .search-box .input-group-text {
            min-width: 35px;
            border: none;
            background: transparent;
            position: absolute;
            right: 0;
            z-index: 9;
            padding: 7px 0 7px 7px;
            height: 100%;
        }
    
        .search-box i {
            color: #a0a5b1;
            font-size: 19px;
        }
    
        .navbar .nav-item i {
            font-size: 18px;
        }
    
        .navbar .dropdown-item i {
            font-size: 16px;
            min-width: 22px;
        }
    
        .navbar .nav-item.show>a {
            background: none !important;
        }
    
        .navbar .dropdown-menu {
            border-radius: 1px;
            border-color: #e5e5e5;
            box-shadow: 0 2px 8px rgba(0, 0, 0, .05);
        }
    
        .navbar .dropdown-menu a {
            color: #777;
            padding: 8px 20px;
            line-height: normal;
            font-size: 15px;
        }
    
        .navbar .navbar-form {
            margin-right: 0;
            margin-left: 0;
            border: 0;
        }
    
        @media (min-width: 992px) {
            .form-inline .input-group {
                width: 250px;
                margin-right: 30px;
            }
        }
    
        @media (max-width: 991px) {
            .form-inline {
                display: block;
                margin-bottom: 10px;
                margin-top: 0;
            }
    
            .input-group {
                width: 100%;
            }
        }
    </style>
    </head>
    
    <body>
        <nav class="navbar navbar-expand-lg navbar-light">
            <a class="navbar-brand" href="#">To<b>DO</b></a>
            <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                <span class="navbar-toggler-icon"></span>
            </button>
            <!-- Collection of nav links, forms, and other content for toggling -->
            <div id="navbarCollapse" class="collapse navbar-collapse justify-content-start">
                <div class="navbar-nav">
                    <a href="/" class="nav-item nav-link">Home</a>
                    <a href="#" class="nav-item nav-link">Contact</a>
                </div>
                <div class="navbar-nav ml-auto">
                    <div class="navbar-form-wrapper">
                        <form class="navbar-form form-inline">
                            
                    </div>
                        </form>
                    </div>
                    <a href="#" class="nav-item nav-link"><i class="fa fa-facebook"></i></a>
                    <a href="#" class="nav-item nav-link"><i class="fa fa-twitter"></i></a>
                    <a href="#" class="nav-item nav-link"><i class="fa fa-google-plus"></i></a>
                    <a href="#" class="nav-item nav-link"><i class="fa fa-pinterest-p"></i></a>
                </div>
            </div>
        </nav>
    <div  class="container mx-auto col-xs-1"  align="center">
     {% block content %}
       
     {% endblock content %}

    </div>






    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
        integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
        crossorigin="anonymous"></script>
</body>

</html>